# Generated by Django 4.1.7 on 2023-03-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.TextField()),
                ('Maxtemp', models.FloatField()),
                ('Mintemp', models.FloatField()),
                ('Precipitation', models.FloatField()),
                ('Station_id', models.TextField()),
            ],
        ),
    ]
