# Generated by Django 4.1.7 on 2023-03-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_weather_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.TextField()),
                ('Yield', models.FloatField()),
            ],
            options={
                'db_table': 'crop_data',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.TextField()),
                ('Station_id', models.TextField()),
                ('Average_Maxtemp', models.FloatField()),
                ('Average_Mintemp', models.FloatField()),
                ('Sum_Precipitation', models.FloatField()),
            ],
            options={
                'db_table': 'weather_stats',
            },
        ),
    ]
